### ISSUE TITLE
Additional Ranger Spell Tracking

### ISSUE THREAD

**Issue by mrhoribu** [elanthia-online/jinx#24]
The following effects were added to SPELL ACTIVE and the Active Spells window:

* [ ] Nature's Bounty Foraging Recovery
* [ ] Barkskin Recovery
* [ ] Barkskin Commune Recovery
* [ ] Tangleweed Vigor
* [ ] Breeze Archery Tailwind
* [ ] Nature's Touch Physical Prowess
* [ ] Nature's Touch Arcane Reflexes
* [ ] Aspect of the [Aspect]

Nature's Touch(625) Arcane Reflexes:
```
START: Vital energy infuses you, hastening your arcane reflexes!
END: Nature's blessing of vitality departs as your arcane prowess returns to normal.
```

Breeze Archery Tailwind(612):
```
START: A favorable tailwind springs up behind you.
END: As abruptly as it began, the tailwind embracing you goes still.
```

**Comment by mrhoribu** [comment]
Nature's Touch(625) Physical Prowess:
```
START: The vitality of nature bestows you with a burst of strength!
END: Nature's blessing of vitality departs as your strength returns to its previous state.
```

**Comment by mrhoribu** [comment]
Nature's Bounty (604) Foraging Recovery (terrain specific, will need additional):
```
START: Glimmers of greenish light ripple away from you and seep into the ice, rioting the surrounding flora to new life.
```

**Comment by mrhoribu** [comment]
Barkskin Recovery
Will need to trigger on cast of 605 to put up whatever # is decided to be used for Barkskin Recovery via Spell.putup in infomon.lic due to no exclusive game txt to trigger start but the initial cast. Also no END messaging in game for when recovery is done.
